---
abstract: 'A usage example for CGI::Ex::App!'
author:
  - 'Красимир Беров <k.berov@gmail.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Ex-Recipes
no_index:
  directory:
    - t
    - inc
requires:
  CGI::Ex: 2.18
  DBD::SQLite: 0
  DBI: 0
  SQL::Abstract: 0
  Test::More: 0
  YAML: 0.65
version: 0.08
