# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Ex-Recipes
version:      0.07
version_from: erecipes/perl/lib/CGI/Ex/Recipes.pm
installdirs:  site
requires:
    CGI::Ex:                       2.18
    DBD::SQLite:                   0
    DBI:                           0
    SQL::Abstract:                 0
    Test::More:                    0
    YAML:                          0.65

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
